package component:aws-sdk-wasi-example;

interface data-uploader {
    resource data-uploader-client {
        constructor(config: client-config);
        upload: func(input: data) -> result<confirmation, error>;
        %list: func() -> result<list<file-metadata>, error>;
    }

    record client-config {
        region: string,
        bucket-name: string,
        table-name: string,
    }

    record data {
        file-name: string,
        data: list<u8>,
        metadata: list<tuple<string, string>>,
    }

    record confirmation {
        s3-uri: string,
    }

    record file-metadata {
        s3-uri: string,
        metadata: list<tuple<string, string>>,
    }

    variant error {
        s3-error(string),
        ddb-error(string),
        input-error(string),
    }

}

world example {
    export data-uploader;
}
